# Generated by Django 5.1.3 on 2024-11-19 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autherName', models.CharField(max_length=30)),
                ('publisher', models.CharField(max_length=30)),
                ('publicationDate', models.DateField()),
                ('description', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=10)),
            ],
        ),
    ]
